language: go

sudo: false

go:
  - 1.13.x

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.21.0

script:
  - make lint
  - make build